### ISSUE TITLE
Inconsistency between adjacency matrices in papers and codes

### ISSUE THREAD

**Issue by cezarbbb** [yipoh/SARQUE#1]
Hello! I' ve read your code and paper.  Congrats on your awesome work! However, I found that the adjacent matrix of your paper mismatches the code you provided('Cora.sites' actually ). I want to know the reason.
Thank you very much!

**Comment by yipoh** [comment]
Many thanks for your attention to our work. The issue you mentioned is due to a discrepancy between versions. We did not use the same sorting in defining the adjacency matrix in the paper and code. For easy to follow, we have uploaded the codes. We greatly appreciate your carefulness and assistance in finding this issue.

**Comment by yipoh** [comment]
> Hello! I' ve read your code and paper. Congrats on your awesome work! However, I found that the adjacent matrix of your paper mismatches the code you provided('Cora.sites' actually ). I want to know the reason. Thank you very much!

Many thanks for your attention to our work. The issue you mentioned is due to a discrepancy between versions. We did not use the same sorting in defining the adjacency matrix in the paper and code. For easy to follow, we have uploaded the codes. We greatly appreciate your carefulness and assistance in finding this issue.
